export const envConfig = {
  WALLET_CONNECT_API_KEY: process.env.NEXT_PUBLIC_WALLET_CONNECT_API_KEY,
  WALLET_APP_NAME: process.env.NEXT_PUBLIC_WALLET_APP_NAME,
  WALLET_APP_DESCRIPTION: process.env.NEXT_PUBLIC_WALLET_APP_DESCRIPTION,
  WALLET_APP_URL: process.env.NEXT_PUBLIC_WALLET_APP_URL,
  WALLET_APP_ICON_URL: process.env.NEXT_PUBLIC_WALLET_APP_ICON_URL,
  NFT_CONTRACT: process.env.NEXT_PUBLIC_NFT_CONTRACT,
  USDC_CONTRACT: process.env.NEXT_PUBLIC_USDC_CONTRACT,
  USDT_CONTRACT: process.env.NEXT_PUBLIC_USDT_CONTRACT,
  CHAIN_ID: process.env.NEXT_PUBLIC_CHAIN_ID,
}
